Improve error message when parsing versions
    ERROR Failed to parse request mypkg/=1.*

    Caused by:
        Error: expected an ascii digit at *

Previously:

    Caused by:
        Error: expected eof at .*

Using the same approach as `cut` on parsing the 2nd or later digits means
that unexpected input can be properly attributed to the version number
being malformed, rather than successfully parsing the version as "1" and
then having unexpected leftover input.

Signed-off-by: J Robert Ray <jrray@jrray.org>