Fix panic when using "x.x.x.x" compat value
Observed as:
pyo3_runtime.PanicException: range end index 4 out of range for slice of length 3

Change from drain to take here and provide an infinite length stream of
zeros to not underrun.

Signed-off-by: J Robert Ray <jrray@imageworks.com>