Handle solution.to_environment(os.environ)
os.environ cannot be passed to a function that takes
HashMap<String, String>:

TypeError: argument 'base': '_Environ' object cannot be converted to 'PyDict'

Signed-off-by: J Robert Ray <jrray@imageworks.com>