Adds basic solver stats and user and automatic interrupt handling
Adds solver timing and error message frequency stats display with
'--time|-t' option to all commands that use solvers. Adds automatic
verbosity increases when the solver runs too long, and checks to halt
the solve after too many increases (both configurable via environment
variables). Adds ctrl-c handling during solver runs so the user can
interrupt the solve and see the solver stats so far. Adds new solver
Error: SolverInterrupted.

Signed-off-by: David Gilligan-Cook <dcook@imageworks.com>