Fix `WildcardRange::less_than`
Add to the property tests to generate test inputs for `WildcardRange`. This
revealed a logic error in `less_than`. It appears to be assuming that the
wildcard is always in the last position of the version parts.

```
proptest: Aborting shrinking after the PROPTEST_MAX_SHRINK_ITERS environment variable or ProptestConfig.max_shrink_iters iterations (set 1024 to a large(r) value to shrink more; current configuration: 1
024 iterations)
thread 'api::version_range::version_range_test::prop_test_range_intersect' panicked at 'Test failed: 1459733284.1408393923+kh7dnFYiyqgrVC7n00Qf2MmSm.2718654106 -- a:*.1408393923 + b:1459733284.140839392
3+kh7dnFYiyqgrVC7n00Qf2MmSm.2718654106 == Incompatible("0.1408393923..1408393924 does not intersect with 1459733284.1408393923+kh7dnFYiyqgrVC7n00Qf2MmSm.2718654106..") at src/api/./version_range_test.rs
:338; minimal failing input: pair = (Version { parts: VersionParts { parts: [1459733284, 1408393923], plus_epsilon: false }, pre: TagSet { tags: {} }, post: TagSet { tags: {"kh7dnFYiyqgrVC7n00Qf2MmSm":
2718654106} } }, Wildcard(WildcardRange { specified: 2, parts: [None, Some(1408393923)] }), Compat(CompatRange { base: Version { parts: VersionParts { parts: [1459733284, 1408393923], plus_epsilon: fals
e }, pre: TagSet { tags: {} }, post: TagSet { tags: {"kh7dnFYiyqgrVC7n00Qf2MmSm": 2718654106} } }, required: None }))
        successes: 3
        local rejects: 7
                7 times at a less than or equal version
        global rejects: 0
', src/api/./version_range_test.rs:329:1
```

Signed-off-by: J Robert Ray <jrray@imageworks.com>