Let `resolve_stack_to_layers` return a `Future` that is `Send`
Otherwise, this is posing a problem for making spk code async, this is
caused by calling `BinaryPackageBuilder::build`:

error: generator cannot be sent between threads safely
   --> src/cli/cmd_make_binary.rs:52:44
    |
52  |       async fn run(&mut self) -> Result<i32> {
    |  ____________________________________________^
53  | |         let _runtime = self.runtime.ensure_active_runtime()?;
54  | |
55  | |         let options = self.options.get_options()?;
...   |
147 | |         Ok(0)
148 | |     }
    | |_____^ future created by async block is not `Send`
    |
    = help: the trait `Send` is not implemented for `dyn Future<Output = std::result::Result<Vec<spfs::graph::Layer>, spfs::Error>>`
    = note: required for the cast to the object type `dyn Future<Output = std::result::Result<i32, anyhow::Error>> + Send`

Signed-off-by: J Robert Ray <jrobertray@gmail.com>