Try adding rustfmt
     Running `/__w/spk/spk/target/debug/build/spfs-a923ddcd38ccfa3b/build-script-build`
error: failed to run custom build command for `spfs v0.34.3 (***github.com/imageworks/spfs?tag=v0.34.3#4750235e)`
Caused by:
  process didn't exit successfully: `/__w/spk/spk/target/debug/build/spfs-a923ddcd38ccfa3b/build-script-build` (exit status: 1)
  --- stderr
  error: 'rustfmt' is not installed for the toolchain '1.61.0-x86_64-unknown-linux-gnu'
  To install, run `rustup component add rustfmt`
warning: build failed, waiting for other jobs to finish...

Signed-off-by: J Robert Ray <jrray@imageworks.com>